[variables]
NODE_VERSION = "24.0.0"
PNPM_VERSION = "9.7.0"
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_24", "pnpm"]

[phases.install]
cmds = [
  "pnpm install --frozen-lockfile --prod=false"
]

[phases.build]
cmds = [
  "pnpm run build"
]

[start]
cmd = "pnpm start"